// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9H494wHd7i64TnMqfXndPlzrpsEPcz9Q',
    appId: '1:59002806726:web:c04610faee8cd95ccad2c7',
    messagingSenderId: '59002806726',
    projectId: 'flutter-pushnotification100day',
    authDomain: 'flutter-pushnotification100day.firebaseapp.com',
    storageBucket: 'flutter-pushnotification100day.appspot.com',
    measurementId: 'G-FPGSJ53G4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDgBqlVi077h7hynXNJaSBbSb1ZsJlMsI',
    appId: '1:59002806726:android:dc7d49799fd68179cad2c7',
    messagingSenderId: '59002806726',
    projectId: 'flutter-pushnotification100day',
    storageBucket: 'flutter-pushnotification100day.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm-CjbEfB7r9goQK1nUq6n3MHBL5hTQIY',
    appId: '1:59002806726:ios:909f53c5f245b69dcad2c7',
    messagingSenderId: '59002806726',
    projectId: 'flutter-pushnotification100day',
    storageBucket: 'flutter-pushnotification100day.appspot.com',
    iosBundleId: 'com.example.flutter100days',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm-CjbEfB7r9goQK1nUq6n3MHBL5hTQIY',
    appId: '1:59002806726:ios:740b6b2b088f2787cad2c7',
    messagingSenderId: '59002806726',
    projectId: 'flutter-pushnotification100day',
    storageBucket: 'flutter-pushnotification100day.appspot.com',
    iosBundleId: 'com.example.flutter100days.RunnerTests',
  );
}
